import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const savedLanguage = localStorage.getItem("i18nextLng") || "uz";

i18n.use(initReactI18next).init({
  resources: {
    uz: {
      translation: {
        "modes": {
          "fast": {
            "label": "Fast",
            "description": "Tezkor savol javob"
          },
          "deep": {
            "label": "Deep",
            "description": "Chuqur tahlil"
          },
          "document": {
            "label": "Hujjatlar",
            "description": "Hujjatlar bo'yicha"
          },
          "web": {
            "label": "Web",
            "description": "Web qidiruv"
          }
        },
        "typeMessage": "Xabar yozing...",
        "askAboutDocument": "Hujjat haqida so'rang...",
        "invalidFileType": "Noto'g'ri fayl turi. Faqat PDF, TXT, DOC, DOCX fayllarini yuklang.",
        "loginToChat": "Suhbat uchun tizimga kiring",
        chatgpt: "Imzo AI",
        login: "Kirish",
        today: "Bugun",
        newChat: "Yangi chat",
        signup: "Bepul ro'yxatdan o'tish",
        pdf: "Ariza yaratish",
        writeApplication: "Ariza yozish",
        generateApplication: "Ariza PDF yaratish",
        downloadApplication: "Arizani yuklab olish",
        askanything: "Har qanday savol bering",
        you: "Siz:",
        "daysAgo": "{count} kun oldin",
        "7daysAgo": "7 kun oldin",
        "daysAgo_1": "1 kun oldin",
        "daysAgo_2": "2 kun oldin",
        "daysAgo_3": "3 kun oldin",
        "daysAgo_4": "4 kun oldin",
        "daysAgo_5": "5 kun oldin",
        "daysAgo_6": "6 kun oldin",
        "daysAgo_7": "7 kun oldin",
        newchat: "Yangi chat",
        chathistory: "Chat tarixi",
        terms: "Shartlar",
        privacy: "Maxfiylik siyosati",
        agree: "Imzo AI bilan xabar yuborish orqali siz bizning",
        loginRequired: "Savollar berish uchun avval login qiling",
        failedtocreatechatroom: "Yangi chat yaratishda xatolik",
        pleasecreatechatroom: "Iltimos yangi chat yarating",
        failedtosendmessage: "Xabar yuborishda xatolik",
        rateLimitError: "Siz juda ko'p so'rov yuboryapsiz. Biroz kuting.",
        serverError: "Server xatoligi yuz berdi. Keyinroq qayta urinib ko'ring.",
        networkError: "Internet aloqasini tekshiring.",
        tokenError: "Autentifikatsiya tokeni topilmadi. Iltimos, qayta login qiling.",
        enterName: "Ismingizni kiriting",
        save: "Saqlash",
        cancel: "Bekor qilish",
        nameRequired: "Iltimos, ismingizni kiriting!",
        nameUpdateError: "Ismni saqlashda xatolik yuz berdi!",
        categories: "Kategoriyalar",
        noItems: "Items yo'q",
        noCategories: "Kategoriyalar topilmadi",
        supportChat: "Qo'llab-quvvatlash suhbati",
        noSupportMessages: "Hali qo'llab-quvvatlash xabarlari yo'q",
        typeSupportMessage: "Xabaringizni yozing...",
        send: "Yuborish",
        supportMessageSent: "Xabar qo'llab-quvvatlashga yuborildi",
        failedToSendSupportMessage: "Qo'llab-quvvatlash xabarini yuborib bo'lmadi",
        userIdNotFound: "Foydalanuvchi identifikatori topilmadi",
        "myApplications": "Mening arizalarim",
        "noApplications": "Hozircha arizalar yo‘q",
        "failedToLoadApplications": "Arizalarni yuklashda xatolik",
        "failedToUpdate": "Nomni o‘zgartirib bo‘lmadi",
        "failedToDelete": "O‘chirib bo‘lmadi",
        "confirmDelete": "Bu arizani o‘chirmoqchimisiz?",
        "edit": "Tahrirlash",
        "delete": "O‘chirish",
        "notifications": "Xabarnomalar",
        "no_notifications": "Xabarnomalar yo'q",
        "mark_all_read": "Hammasini o'qilgan deb belgilash",
        "invalidFileType": "Noto'g'ri fayl turi. Faqat PDF, TXT, DOC yoki DOCX fayllari qabul qilinadi.",
        "uploadFile": "Fayl yuklash",
        "askAboutDocument": "Hujjat haqida so'rov yuboring",
        "typeMessage": "Xabar yozing...",
        "loginToChat": "Suhbatlashish uchun tizimga kiring",
        "loginPrompt": "Imzo AI bilan davom etish uchun ro'yxatdan o'ting yoki tizimga kiring",
        "pleaseLogin": "Iltimos, tizimga kiring"
      },
    },
    ru: {
      translation: {
        "modes": {
          "fast": {
            "label": "Быстрый",
            "description": "Быстрый вопрос-ответ"
          },
          "deep": {
            "label": "Глубокий",
            "description": "Глубокий анализ"
          },
          "document": {
            "label": "Документы",
            "description": "По документам"
          },
          "web": {
            "label": "Веб",
            "description": "Веб-поиск"
          }
        },
        "typeMessage": "Введите сообщение...",
        "askAboutDocument": "Задайте вопрос о документе...",
        "invalidFileType": "Неверный тип файла. Загружайте только PDF, TXT, DOC, DOCX файлы.",
        "loginToChat": "Войдите в систему для общения",
        chatgpt: "Imzo AI",
        login: "Вход",
        newChat: "Новый чат",
        signup: "Бесплатная регистрация",
        pdf: "Создать заявление",
        writeApplication: "Написать заявление",
        generateApplication: "Создать PDF заявления",
        downloadApplication: "Скачать заявление",
        askanything: "Задайте любой вопрос",
        you: "Вы:",
        supportChat: "Чат службы поддержки",
        noSupportMessages: "Пока нет сообщений службы поддержки",
        typeSupportMessage: "Введите сообщение...",
        send: "Отправить",
        supportMessageSent: "Сообщение отправлено в службу поддержки",
        failedToSendSupportMessage: "Не удалось отправить сообщение службы поддержки",
        userIdNotFound: "Идентификатор пользователя не найден",
        today: "Сегодня",
        newchat: "Новый чат",
        chathistory: "История чатов",
        terms: "Условия",
        "daysAgo_1": "1 день назад",
        "daysAgo_2": "2 дня назад",
        "daysAgo_3": "3 дня назад",
        "daysAgo_4": "4 дня назад",
        "daysAgo_5": "5 дней назад",
        "daysAgo_6": "6 дней назад",
        "daysAgo_7": "7 дней назад",
        privacy: "Политика конфиденциальности",
        agree: "Отправляя сообщение Imzo AI, вы соглашаетесь с нашими",
        loginRequired: "Для отправки вопросов сначала войдите в систему",
        failedtocreatechatroom: "Ошибка при создании нового чата",
        pleasecreatechatroom: "Пожалуйста, создайте новый чат",
        failedtosendmessage: "Ошибка при отправке сообщения",
        rateLimitError: "Слишком много запросов. Подождите немного.",
        serverError: "Произошла ошибка сервера. Попробуйте позже.",
        networkError: "Проверьте подключение к интернету.",
        "myApplications": "Мои заявления",
        "untitled": "Без названия",
        "unknownDate": "Неизвестная дата",
        "noConversations": "Нет бесед",
        "noApplications": "Пока нет заявлений",
        "failedToLoadApplications": "Ошибка загрузки заявлений",
        "failedToUpdate": "Не удалось изменить имя",
        "failedToDelete": "Не удалось удалить",
        "confirmDelete": "Вы уверены, что хотите удалить это заявление?",
        "edit": "Редактировать",
        "delete": "Удалить",
        tokenError: "Токен аутентификации не найден. Пожалуйста, войдите снова.",
        enterName: "Введите ваше имя",
        save: "Сохранить",
        cancel: "Отмена",
        "daysAgo": "{count} дней назад",
        "7daysAgo": "7 дней назад",
        nameRequired: "Пожалуйста, введите ваше имя!",
        nameUpdateError: "Ошибка при сохранении имени!",
        categories: "Категории",
        noItems: "Нет элементов",
        noCategories: "Категории не найдены",
        "notifications": "Уведомления",
        "no_notifications": "Нет уведомлений",
        "mark_all_read": "Отметить все как прочитанные",
        "invalidFileType": "Недопустимый тип файла. Поддерживаются только файлы PDF, TXT, DOC или DOCX.",
        "uploadFile": "Загрузить файл",
        "askAboutDocument": "Задайте вопрос о документе",
        "typeMessage": "Введите сообщение...",
        "loginToChat": "Войдите, чтобы начать чат",
        "loginPrompt": "Войдите или зарегистрируйтесь, чтобы продолжить с Imzo AI",
        "pleaseLogin": "Пожалуйста, войдите в систему"
      },
    },
  },
  lng: savedLanguage, // Use saved language or default to "uz"
  fallbackLng: "uz",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;